use std::{fs, mem, rc::Rc};

use anyhow::Result;
use crossterm::event::KeyCode;
use indoc::{formatdoc, indoc};
use ratatui::layout::{Constraint, Layout, Rect};

use crate::tui::{
    widgets::menu::{to_string_vec, MenuView},
    TuiBackend, TuiCommand,
};

use super::{vertical_layout, View};

type GroupedMirror = (Rc<String>, Vec<Rc<String>>);

const FIRST_GROUP: &str = "# Default mirrors";

fn get_grouped_mirrors() -> Result<Vec<GroupedMirror>> {
    let mirror_list = fs::read_to_string("./mirrorlist")?;

    let mut group = Rc::new(FIRST_GROUP.to_string());
    let mut servers = vec![];
    let mut result = vec![];

    for line in mirror_list
        .lines()
        .skip_while(|line| !line.starts_with(FIRST_GROUP))
        .skip(1)
    {
        if line.starts_with("Server") {
            // remove "$repo/os/$arch" 14
            // remove "Server = " 9
            servers.push(Rc::new(line.to_owned()))
        } else if line.starts_with("# ") {
            result.push((
                mem::replace(&mut group, Rc::new(line.to_owned())),
                mem::take(&mut servers),
            ))
        }
    }

    result.push((group, servers));

    Ok(result)
}

#[derive(Debug, Clone, Copy)]
enum MenuTab {
    MirrorType,
    MirrorGroup,
    SingleMirror,
}

pub struct Mirror {
    menus: [MenuView; 3],
    layout: Layout,
    tab: MenuTab,
    need_update: bool,
    grouped_mirrors: Vec<GroupedMirror>,
}

impl Mirror {
    const MIRROR_TYPES: [&str; 2] = ["Mirror group", "Single mirror"];
    const FILE_HEADER: &str = indoc! {"
        ##
        ## Mirrorlist generated by Artixide
        ##
    "};

    pub fn new() -> Self {
        let menus = [
            MenuView::new(to_string_vec(Self::MIRROR_TYPES)),
            MenuView::new([]),
            MenuView::new([]),
        ];

        let layout = vertical_layout([
            Constraint::Length(5),
            Constraint::Min(4),
            Constraint::Length(1),
        ]);

        Self {
            menus,
            layout,
            tab: MenuTab::MirrorType,
            need_update: true,
            grouped_mirrors: vec![],
        }
    }

    fn get_menu_mut(&mut self) -> &mut MenuView {
        &mut self.menus[self.tab as usize]
    }

    fn current_item(&self) -> Option<Rc<String>> {
        self.menus[self.tab as usize].current_item()
    }
}

impl View<TuiBackend> for Mirror {
    fn on_event(
        &mut self,
        event: crossterm::event::KeyEvent,
        config: &mut crate::config::Config,
    ) -> Option<crate::tui::TuiCommand> {
        let menu = self.get_menu_mut();

        match event.code {
            KeyCode::Esc | KeyCode::Char('q') => match self.tab {
                MenuTab::MirrorGroup | MenuTab::SingleMirror => {
                    self.tab = MenuTab::MirrorType;
                    None
                }
                MenuTab::MirrorType => Some(TuiCommand::BackToMain),
            },
            KeyCode::Enter => {
                let cur = self.current_item()?;

                match self.tab {
                    MenuTab::MirrorType => match cur.as_str() {
                        "Mirror group" => self.tab = MenuTab::MirrorGroup,
                        "Single mirror" => self.tab = MenuTab::SingleMirror,
                        _ => unreachable!(),
                    },
                    MenuTab::MirrorGroup => {
                        let item = self.current_item()?;

                        let (group, servers) = self
                            .grouped_mirrors
                            .iter()
                            .find(|(group, _)| group == &item)
                            .unwrap();

                        let servers = servers
                            .iter()
                            .map(|s| s.as_str())
                            .collect::<Vec<_>>()
                            .join("\n");

                        let mirror = formatdoc! {"
                            {}
                            {}
                            {}
                        ", Self::FILE_HEADER, group, servers};

                        config.mirror = mirror;

                        return Some(TuiCommand::BackToMain);
                    }
                    MenuTab::SingleMirror => {
                        let item = self.current_item()?;

                        let mirror = formatdoc! {"
                            {}
                            {}
                        ", Self::FILE_HEADER, item};

                        config.mirror = mirror;

                        return Some(TuiCommand::BackToMain);
                    }
                };

                None
            }
            _ => menu.on_event(event),
        }
    }

    fn render(&mut self, frame: &mut ratatui::Frame<TuiBackend>) -> anyhow::Result<()> {
        let chunks = self.layout.split(frame.size());

        let tab = self.tab;

        if self.need_update {
            self.grouped_mirrors = get_grouped_mirrors()?;

            let (group, servers): (Vec<_>, Vec<_>) = self.grouped_mirrors.iter().cloned().unzip();

            let default_servers_count = servers[0].len();

            let servers = servers
                .into_iter()
                .flatten()
                .skip(default_servers_count)
                .collect::<Vec<_>>();

            let menu = &mut self.menus[MenuTab::MirrorGroup as usize];
            menu.replace_items(group);

            let menu = &mut self.menus[MenuTab::SingleMirror as usize];
            menu.replace_items(servers);

            self.need_update = false;
        }

        let mut menu_area: Rect = chunks[1];

        if let MenuTab::MirrorType = tab {
            menu_area =
                vertical_layout([Constraint::Length(4), Constraint::Min(1)]).split(chunks[1])[0];
        }

        let menu: &mut MenuView = self.get_menu_mut();

        match tab {
            MenuTab::MirrorGroup => menu.render_with(frame, menu_area, |i| &i[2..]),
            MenuTab::SingleMirror => menu.render_with(frame, menu_area, |i| {
                let len = i.len();
                &i[9..len - 14]
            }),
            MenuTab::MirrorType => menu.render(frame, menu_area),
        }

        menu.render_searchbar(frame, chunks[2]);

        Ok(())
    }
}
